name: 1.1$(Rev:.r)

trigger:
- main

pool: "Azure DevOps Server 2022"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vsix: '$(Build.ArtifactStagingDirectory)/vsix/gate-condition-editor-$(Build.BuildNumber).vsix'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2.211.0
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ServerTaskExpressionTester/bin/$(buildConfiguration)'
    Contents: |
      *.pdb
      *.exe
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: NodeTool@0.213.0
  inputs:
    versionSpec: '10.x'
    checkLatest: true

- task: TfxInstaller@5
  inputs:
    version: 'v0.x'

- task: PackageAzureDevOpsExtension@5
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    outputPath: '$(vsix)'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: false
    
- task: PublishAzureDevOpsExtension@5
  inputs:
    connectTo: 'AzureRM'
    connectedServiceNameAzureRM: azure-devops-marketplace
    fileType: 'vsix'
    vsixFile: '$(vsix)'
    updateTasksVersion: false
    noWaitValidation: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Output'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GitHub - jessehouwing'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
